[build]
  command = "npm run build"
  publish = "dist"

# SPA routing for React Router on Netlify
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
